nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
        - node4:node4
    ports:
        - "8000:8000"
node1:
    build: ./node
    ports:
        - "3000"
    restart: always
node2:
    build: ./node
    ports:
        - "3000"
    restart: always
node3:
    build: ./node
    ports:
        - "3000"
    restart: always
node4:
    build: ./node
    ports:
        - "3000"
    restart: always
